### ISSUE TITLE
Not working on Microsoft EDGE

### ISSUE THREAD

**Issue by TonyHenrique** [Minishlink/pwa-qr-code-scanner#3]
When I open on Microsoft EDGE (I tested on Desktop and also Mobile)
this error appears on Console
```
SCRIPT438: Object doesn't support property or method 'vibrate'
app.js (79,13)
```

**Comment by LightWayUp** [comment]
The main feature which is reading QR Code does work on Microsoft Edge. It's the vibration API that isn't supported. I don't think it is a big issue, however - after all, Internet Explorer, Opera and Safari don't support that either.
