### ISSUE TITLE
IOS PWA shows "Sorry, your browser is not compatible with this app".

### ISSUE THREAD

**Issue by abcfy2** [Minishlink/pwa-qr-code-scanner#9]
What's wrong with this PWA? Thanks.

![image](https://user-images.githubusercontent.com/5327677/55957588-4e01c000-5c99-11e9-86ee-7f978e8e9864.png)

**Comment by Minishlink** [comment]
See https://github.com/Minishlink/pwa-qr-code-scanner/blob/be1bb376a7fa3ea451ee21d21fcad900603f5995/app/assets/app.js#L5

**Comment by abcfy2** [comment]
Seems that IOS Safari does not support this feature. Thanks.

**Comment by quornik** [comment]
Trying to use the app in latest Chrome on Android, and it still does not work, shows the "not compatible" error.
